name: Deploy to EKS

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v3

    - name: Check out code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Get SSM parameters
      uses: dkershner6/aws-ssm-getparameters-action@v2
      with:
          parameterPairs: "/deploy/primary/region = PRIMARY_AWS_REGION,
                           /deploy/primary/kubernetes_cluster = PRIMARY_KUBER_CLUSTER,
                           /deploy/secondary/region = SECONDARY_AWS_REGION,
                           /deploy/secondary/kubernetes_cluster = SECONDARY_KUBER_CLUSTER,
                           /deploy/ecr_repository = ECR_REPOSITORY"

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
        REPO_NAME: "poc-app"
      run: |
        docker build -t "$ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG" -f Dockerfile .
        docker push "$ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG"

    - name: Deploy to primary
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
      run: |
        aws eks update-kubeconfig --name $PRIMARY_KUBER_CLUSTER --region $PRIMARY_AWS_REGION
        sed -i.bak "s|DOCKER_IMAGE|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" manifests/deployment.yaml
        kubectl apply -f manifests/deployment.yaml

    - name: Deploy to secondary
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
      run: |
        aws eks update-kubeconfig --name $SECONDARY_KUBER_CLUSTER --region $SECONDARY_AWS_REGION
        sed -i.bak "s|DOCKER_IMAGE|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" manifests/deployment.yaml
        kubectl apply -f manifests/deployment.yaml
